### ISSUE TITLE
no dollar price is displayed for high-priced assets

### ISSUE THREAD

**Issue by maxjuno** [Wasmswap/wasmswap-interface#163]
example picture:
![fsfsfsf](https://user-images.githubusercontent.com/98474118/152835759-4d0e6230-8cb3-4c3f-849a-91599d93f04c.jpg)

**Comment by sashimi36** [comment]
Hey @maxjuno! Thanks this seems like a bad bug. I think this might have to do something with the "id" that is used in the token list for this particular asset. That field represents coin gecko id (i know it's confusing). If people choose to leave the id an empty string then the price would have been calculated based on the token to token ratio. Hope that helps!

**Comment by maxjuno** [comment]
makes sense, 
thanks for clarifying @sashimi36 
now it works :)

i close it
