### ISSUE TITLE
[suggestion] transfer window always at the top could be confusing later on

### ISSUE THREAD

**Issue by maxjuno** [Wasmswap/wasmswap-interface#192]
the transfer window is always at the top, it could be confusing later on once more assets are supported

![Inkedemoney mainnet_LI](https://user-images.githubusercontent.com/98474118/161437778-b65c6833-5614-4b0d-8272-4ab17fc861ff.jpg)

![Inkedemoney mainnet2_LI](https://user-images.githubusercontent.com/98474118/161437785-bc0ddaa1-9686-4675-8cdc-e2455dbf1ca1.jpg)

**Comment by rawasabi** [comment]
this is fixed on testnet @maxjuno
